### ISSUE TITLE
Bei Verwendung von "ipmc_SEPADirectDebit" fehlt die IBAN in der Testrechnung / beim Einlesen

### ISSUE THREAD

**Issue by dsshad** [LandrixSoftware/XRechnung-for-Delphi#18]
Hallo,
ich habe eine ZUGFeRD-Rechnung mit "Lastschrift" als Zahlungsbedingung erzeugt. Dabei wird beim Abgleich der Testrechnung mit dem Original gemeldet, dass diese unterschiedlich sind. In der Testrechnung fehlt dieser eingerahmte Bereich:

![lastschrift_iban](https://github.com/user-attachments/assets/791dc159-0196-4a8a-8921-62a05a252a05)

Dementsprechend fehlt die IBAN in "inv.PaymentFinancialAccount" auch beim Einlesen dieser Rechnung, wenn ich so tue, als ob das eine Eingangsrechnung wäre.

**Comment by landrix** [comment]
behoben, danke
