### ISSUE TITLE
In "intf.XRechnung" wird noch ".InvoiceReferencedDocument" verwendet

### ISSUE THREAD

**Issue by dsshad** [LandrixSoftware/XRechnung-for-Delphi#19]
Hallo,
mit dem neuen Release scheint noch nicht alles zu passen. Die Compilierung stoppt bei "if _InvoiceDescriptor.InvoiceReferencedDocument <> nil then" weil es "InvoiceReferencedDocument" nicht mehr gibt. Das war ja eine der Änderungen, soweit ich gesehen habe.

**Comment by PeterSawatzki-MGGM** [comment]
Ich habe das bei mir durch InvoiceReferencedDocument**s**.Count>0 ersetzt

**Comment by landrix** [comment]
Im aktuellen source ist es behoben, ich mach das release noch einmal neu 
Danke
