### ISSUE TITLE
Validierung von XML-Dateien mit Leerzeichen im Namen

### ISSUE THREAD

**Issue by dsshad** [LandrixSoftware/XRechnung-for-Delphi#23]
Hallo,
kann es sein, dass mit dem letzten Update sich etwas an der Validierung von XML-Dateien mit Leerzeichen im Namen geändert hat?

Ich habe z.B. eine Rechnung im UBL-Format mit diesem Namen erstellt: "Rechnung Nr. 236, Computer ABC (3).xml"
Beim Validieren werden in "TXRechnungValidationHelperJava.ValidateFile" nach Aufruf von "Result := ExecAndWait(_InvoiceXMLFilename+'.bat','');" diese zwei Dateien erzeugt:
"Rechnung%20Nr.%20236,%20Computer%20ABC%20(3)-report.html"
"Rechnung%20Nr.%20236,%20Computer%20ABC%20(3)-report.xml"

Zum Einlesen der Ergebnisse wird aber der Originalname + '-report.xml' bzw. + '-report.html' verwendet, sprich der Name mit Leerzeichen statt %20, sodass die Ergebnisse leer sind.

Der Validator von portinvoice hatte nur gemeckert, als meine XML-Datei in "UTF8 mit BOM" kodiert war, während der Inhalt auf nur "UTF8" deutete (sinngemäß). Dann habe ich die Speicherung auf nur "UTF8" geändert und dann meckerte er nicht mehr, Leerzeichen im Namen scheinen ihm egal zu sein.

Ich hätte jetzt gesagt, dass es vor dem Update funktioniert hat, aber die Unit "intf.XRechnungValidationHelperJava.pas" und auch der Validator selbst sind unverändert geblieben, sodass ich nun nicht sicher bin. Darf der Dateiname keine Leerzeichen enthalten oder stimmt doch irgendwo was nicht?

**Comment by landrix** [comment]
Fehler behoben
