### ISSUE TITLE
TInvoiceUnitCodeHelper.MapUnitOfMeasure with empty _UnitOfMeasure should return _Success:=false

### ISSUE THREAD

**Issue by MicrotronX** [LandrixSoftware/XRechnung-for-Delphi#24]
IMHO the _Success should be false when _UnitOfMeasue = '', right?

class function TInvoiceUnitCodeHelper.MapUnitOfMeasure(_UnitOfMeasure: String; out _Success: Boolean;
  _DefaultOnFailure: TInvoiceUnitCode): TInvoiceUnitCode;
begin
  Result := _DefaultOnFailure;
  _Success := false;
  _UnitOfMeasure := Trim(_UnitOfMeasure);
  if _UnitOfMeasure = '' then
  begin
    _Success := true; ->> sollte doch false sein??
    exit;
  end;
 --- snip ---

**Comment by landrix** [comment]
done
