### ISSUE TITLE
PaymentMeansCode kann nicht mit ipmc_CreditCard genutzt werden

### ISSUE THREAD

**Issue by BlueStarHH** [LandrixSoftware/XRechnung-for-Delphi#32]
Wenn PaymentMeansCode = ipmc_CreditCard müssen diese Felder gefüllt werden:

BT-88: Payment card holder name (Name des Karteninhabers)
BT-87: Payment card primary account number (Die Nummer der Kreditkarte, die für die Zahlung genutzt wurde)

Diese Felder sind jedoch nicht implementiert.

**Comment by landrix** [comment]
done
