### ISSUE TITLE
demodata xRechnung_UBL.xml not working

### ISSUE THREAD

**Issue by coberaland** [LandrixSoftware/XRechnung-for-Delphi#38]
the file ZUGFeRD-for-Delphi/tree/main/demodata/xRechnung/xRechnung UBL.xml

generates the following error message:
`Im Projekt  ist eine Exception der Klasse EOleException mit der Meldung 'Der Eigenschaftswert von SelectionNamespaces ist ungültig.  Nur wohlgeformte xmlns-Attribute sind zugelassen' aufgetreten.`

**Comment by landrix** [comment]
Das ist noch XRechnung v1.2, die schon lange nicht mehr gültig ist. Kann eigentlich gelöscht werden.
