### ISSUE TITLE
XRechnungVersion_220_UBL erzeugt auch XML im Format 2.3

### ISSUE THREAD

**Issue by oldwired** [LandrixSoftware/XRechnung-for-Delphi#4]
Mit `XRechnungVersion_220_UBL` erzeugte XRechnungen werden vom Empfänger mit unbekanntem Format abgelehnt. Ein Blick in die Datei zeigt, dass diese mit `urn:cen.eu:en16931:2017#compliant#urn:xoev-de:kosit:standard:xrechnung_2.3` erzeugt werden.

**Comment by landrix** [comment]
Das aktuellste commit erzeugt XRechnung 2.3, welches ab August gültig ist. Scheint aber noch einen Fehler zu enthalten

Für XRechnung 2.2 bitte die Quellen aus dem Release verwenden

**Comment by oldwired** [comment]
Danke, ist kein großes Problem. Dann sollte für ein Release noch die 2.2 Auswahlkonstante entfernt werden.

**Comment by landrix** [comment]
behoben im aktuellen Release
