### ISSUE TITLE
<ns0:Invoice... werden nicht in TXRechnungValidationHelper.GetXRechnungVersion() als gültig erkannt

### ISSUE THREAD

**Issue by SIDOMO-LU** [LandrixSoftware/XRechnung-for-Delphi#42]
Wenn eine X-Rechnung von dieser Seite (https://ref.xrechnung.bund.de/ref/authenticate.do) erstellt wird, sieht die erzeugte XML-Datei wie folgt aus:

![image](https://github.com/user-attachments/assets/ce103e6f-e083-453c-8f6c-719ed9d70398)

Wegen <ns0:Invoice xmlns:n... wird diese XML-Datei in TXRechnungValidationHelper.GetXRechnungVersion() jedoch nicht als gültig erkannt.

**Comment by landrix** [comment]
Hab mal was ergänzt, hilft das? Wird der Rest der Rechnung dann eingelesen?

**Comment by SIDOMO-LU** [comment]
Danke, passt.
