### ISSUE TITLE
Line breaks are not represented in XML

### ISSUE THREAD

**Issue by VersionReview** [LandrixSoftware/XRechnung-for-Delphi#43]
Hello,
during testing of the examples, it was noticed: Line breaks are not represented in XML.

Source: https://github.com/LandrixSoftware/XRechnung-for-Delphi/blob/master/Samples/XRechnungUnit2TestCases.pas
![image](https://github.com/user-attachments/assets/3b25d746-27e8-433d-8090-7a39c9118579)

In the generated XML, it looks like this:

![image](https://github.com/user-attachments/assets/2c518ea4-531e-42be-bdc5-370997719b6e)

**Comment by landrix** [comment]
Not in my Delphi version. Which one are you using?

![image](https://github.com/user-attachments/assets/c76bce64-2208-4650-9d67-8b8c4d8eb55d)

**Comment by landrix** [comment]
which chars are between 
"..Artikel 2" and "Zeile 2.."
"..Zeile 2" and "Zeile 3.."

**Comment by landrix** [comment]
`<ram:Description>Langtext Artikel Zeile 2 Zeile 3</ram:Description>`

There seems to be a space between the line breaks. What character is it really? (Hex code)

**Comment by landrix** [comment]
So it will be a viewer issue. I think we can close here.

**Comment by landrix** [comment]
> Yeah i think so. If you visualize your XML as a HTML / PDF invoice: line breaks are also missing in HTML and PDF?

Yes
