### ISSUE TITLE
LineOne bei Anschriften ohne Straße

### ISSUE THREAD

**Issue by dsshad** [LandrixSoftware/XRechnung-for-Delphi#44]
Scheinbar gibt es Adressen ohne Straße (keine Postfächer o.ä.). Habe noch keine Info, was das für eine Adresse ist, aber LineOne, wo .AccountingCustomerParty.Address.StreetName eingetragen wird, scheint kein Pflichtfeld zu sein. Das Element darf zwar nicht leer sein, wenn es da ist, aber wenn es gar nicht da ist, meldet der Validator kein Problem.

Aktuell wird LineOne immer fest erzeugt, unabhängig vom Inhalt. Könnte man für so einen Fall vielleicht nur dann eintragen, wenn die Straße angegeben ist.

**Comment by landrix** [comment]
done
